version: 2
jobs:
  test-job:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: typescript
          command: npm run tsc
      - run:
          name: test
          command: npm run jest
      - run:
          name: size-limit
          command: npm run size
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-job
